### ISSUE TITLE
Project License, Mariaex and crawling errors

### ISSUE THREAD

**Issue by machineloop** [praxis-of-nines/zam-search#1]
Hi @Tyler-pierce , thanks for your work on this project, I stumbled across it and thought I'd poke around a bit and try to give it a spin. I'm also curious whether you'd be willing to drop a LICENSE file in the project, as well as in khafra-search project, just to make sure I'm not infringing on your work.

I created a new Ubuntu VM, followed the documented steps to get dev up and running, used the example_config to setup connection to Postgres which looks like it's all good.

I'm a bit confused what Mariaex is being used for since I'm on Postgres... and not sure what I'm missing with the crawler that's preventing it from reaching an example url to crawl like elixirforum.com?

I understand if this a project you've long since abandoned, if so, no worries. I am interested in getting an index up and running to play with it, as well as updating the LiveViews to the latest version, would be happy to contribute back PRs if you're interested.

I'm fairly new to Elixir, so may not be much help working on features at this point, but enjoying poking around your work so far, thanks again!

Here's a command line dump of the errors I encounter when running **mix zam.crawler.crawl all** after **mix zam.create.domain "https://elixirforum.com"**:
```
$:~/zam-search$ mix zam.crawler.crawl all
[debug] Crawlie.Application started
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (stdlib 3.13) supervisor.erl:301: :supervisor.init/1
  (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
  (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (libring 1.4.0) lib/app.ex:13: HashRing.App.start/2
  (kernel 7.0) application_master.erl:277: :application_master.start_it_old/4

[info] [swarm on nonode@nohost] [tracker:init] started
[error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.
[warn] Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.9) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.13) supervisor.erl:1171: :supervisor.children_map/4
  (stdlib 3.13) supervisor.erl:321: :supervisor.init_children/2
  (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
  (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.9) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.13) supervisor.erl:1171: :supervisor.children_map/4
  (stdlib 3.13) supervisor.erl:321: :supervisor.init_children/2
  (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
  (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.9) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.13) supervisor.erl:1171: :supervisor.children_map/4
  (stdlib 3.13) supervisor.erl:321: :supervisor.init_children/2
  (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
  (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.9) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.13) supervisor.erl:1171: :supervisor.children_map/4
  (stdlib 3.13) supervisor.erl:321: :supervisor.init_children/2
  (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
  (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.9) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.13) supervisor.erl:1171: :supervisor.children_map/4
  (stdlib 3.13) supervisor.erl:321: :supervisor.init_children/2
  (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
  (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.9) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
  (stdlib 3.13) supervisor.erl:1171: :supervisor.children_map/4
  (stdlib 3.13) supervisor.erl:321: :supervisor.init_children/2
  (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
  (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

[error] Mariaex.Protocol (#PID<0.510.0>) failed to connect: ** (Mariaex.Error) tcp connect: econnrefused
[error] Mariaex.Protocol (#PID<0.510.0>) failed to connect: ** (Mariaex.Error) tcp connect: econnrefused
[info] [swarm on nonode@nohost] [tracker:cluster_wait] joining cluster..
[info] [swarm on nonode@nohost] [tracker:cluster_wait] no connected nodes, proceeding without sync
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering Khafra.Scheduler.TaskRegistry as process started by Elixir.Quantum.TaskRegistry.start_link/1 with args [%Quantum.TaskRegistry.StartOpts{name: Khafra.Scheduler.TaskRegistry}]
[debug] [swarm on nonode@nohost] [tracker:do_track] starting Khafra.Scheduler.TaskRegistry on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:do_track] started Khafra.Scheduler.TaskRegistry on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering Khafra.Scheduler.JobBroadcaster as process started by Elixir.Quantum.JobBroadcaster.start_link/1 with args [%Quantum.JobBroadcaster.StartOpts{debug_logging: true, jobs: [%Quantum.Job{name: #Reference<0.105587747.718798850.110394>, overlap: true, run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[0 0 * * * *], state: :active, task: {Khafra.Job.Index, :run, [[option: "--rotate", option: "--all"]]}, timezone: "America/Los_Angeles"}], name: Khafra.Scheduler.JobBroadcaster, scheduler: Khafra.Scheduler, storage: Quantum.Storage.Noop}]
[debug] [swarm on nonode@nohost] [tracker:do_track] starting Khafra.Scheduler.JobBroadcaster on nonode@nohost
[debug] [:nonode@nohost][Elixir.Quantum.JobBroadcaster] Loading Initial Jobs from Config
[debug] [swarm on nonode@nohost] [tracker:do_track] started Khafra.Scheduler.JobBroadcaster on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering Khafra.Scheduler.ExecutionBroadcaster as process started by Elixir.Quantum.ExecutionBroadcaster.start_link/1 with args [%Quantum.ExecutionBroadcaster.StartOpts{debug_logging: true, job_broadcaster_reference: {:via, :swarm, Khafra.Scheduler.JobBroadcaster}, name: Khafra.Scheduler.ExecutionBroadcaster, scheduler: Khafra.Scheduler, storage: Quantum.Storage.Noop}]
[debug] [swarm on nonode@nohost] [tracker:do_track] starting Khafra.Scheduler.ExecutionBroadcaster on nonode@nohost
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Unknown last execution time, using now
[debug] [swarm on nonode@nohost] [tracker:do_track] started Khafra.Scheduler.ExecutionBroadcaster on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering #PID<0.517.0> as :"Elixir.#Reference<0.105587747.718798850.110539>", with metadata %{}
[debug] [swarm on nonode@nohost] [tracker:handle_call] add_meta {nil, true} to #PID<0.517.0>
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Adding job #Reference<0.105587747.718798850.110394>
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering Zam.Scheduler.TaskRegistry as process started by Elixir.Quantum.TaskRegistry.start_link/1 with args [%Quantum.TaskRegistry.StartOpts{name: Zam.Scheduler.TaskRegistry}]
[debug] [swarm on nonode@nohost] [tracker:do_track] starting Zam.Scheduler.TaskRegistry on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:do_track] started Zam.Scheduler.TaskRegistry on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering Zam.Scheduler.JobBroadcaster as process started by Elixir.Quantum.JobBroadcaster.start_link/1 with args [%Quantum.JobBroadcaster.StartOpts{debug_logging: true, jobs: [%Quantum.Job{name: #Reference<0.105587747.718798850.110568>, overlap: true, run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[0 * * * * *], state: :active, task: {Zam.Crawler, :crawl, [:hourly]}, timezone: :utc}, %Quantum.Job{name: #Reference<0.105587747.718798850.110569>, overlap: true, run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[0 0 * * * *], state: :active, task: {Zam.Crawler, :crawl, [:daily]}, timezone: :utc}, %Quantum.Job{name: #Reference<0.105587747.718798850.110570>, overlap: true, run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[0 0 * * 0 *], state: :active, task: {Zam.Crawler, :crawl, [:weekly]}, timezone: :utc}, %Quantum.Job{name: #Reference<0.105587747.718798850.110571>, overlap: true, run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster}, schedule: ~e[0 0 1 * * *], state: :active, task: {Zam.Crawler, :crawl, [:monthly]}, timezone: :utc}], name: Zam.Scheduler.JobBroadcaster, scheduler: Zam.Scheduler, storage: Quantum.Storage.Noop}]
[debug] [swarm on nonode@nohost] [tracker:do_track] starting Zam.Scheduler.JobBroadcaster on nonode@nohost
[debug] [:nonode@nohost][Elixir.Quantum.JobBroadcaster] Loading Initial Jobs from Config
[debug] [swarm on nonode@nohost] [tracker:do_track] started Zam.Scheduler.JobBroadcaster on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering Zam.Scheduler.ExecutionBroadcaster as process started by Elixir.Quantum.ExecutionBroadcaster.start_link/1 with args [%Quantum.ExecutionBroadcaster.StartOpts{debug_logging: true, job_broadcaster_reference: {:via, :swarm, Zam.Scheduler.JobBroadcaster}, name: Zam.Scheduler.ExecutionBroadcaster, scheduler: Zam.Scheduler, storage: Quantum.Storage.Noop}]
[debug] [swarm on nonode@nohost] [tracker:do_track] starting Zam.Scheduler.ExecutionBroadcaster on nonode@nohost
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Unknown last execution time, using now
[debug] [swarm on nonode@nohost] [tracker:do_track] started Zam.Scheduler.ExecutionBroadcaster on nonode@nohost
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering #PID<0.526.0> as :"Elixir.#Reference<0.105587747.718798849.108863>", with metadata %{}
[debug] [swarm on nonode@nohost] [tracker:handle_call] add_meta {nil, true} to #PID<0.526.0>
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Adding job #Reference<0.105587747.718798850.110568>
Attempting to crawl all active URL's
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Adding job #Reference<0.105587747.718798850.110569>
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Adding job #Reference<0.105587747.718798850.110570>
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Adding job #Reference<0.105587747.718798850.110571>
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Continuing Execution Broadcasting at -576459570418 (2020-05-17T05:00:00)
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Continuing Execution Broadcasting at -576452370418 (2020-05-17T07:00:00)
[debug] QUERY OK source="indices" db=3.8ms decode=0.9ms queue=0.8ms
SELECT i0."id", i0."webdomain_id", i0."depth", i0."interval_index", i0."interval_cache", i0."active", i0."inserted_at", i0."updated_at", w1."id", w1."domain", w1."score_link", w1."score_zam", w1."inserted_at", w1."updated_at" FROM "indices" AS i0 INNER JOIN "webdomains" AS w1 ON i0."webdomain_id" = w1."id" WHERE (i0."active" = 1) []
[debug] QUERY OK source="bookmarks" db=0.6ms queue=0.7ms
SELECT b0."id", b0."domain_id", b0."bookmark_link", b0."inserted_at", b0."updated_at" FROM "bookmarks" AS b0 WHERE (b0."domain_id" = $1) [1]
[error] Mariaex.Protocol (#PID<0.510.0>) failed to connect: ** (Mariaex.Error) tcp connect: econnrefused
[info] After 4 retries, failed to fetch https://elixirforum.com.
"Finished crawling everything!"
```

**Comment by Tyler-pierce** [comment]
Happy to see interest in these projects. I enjoy them very much and do think they are a good tinker project for practicing elixir. Let me answer a few of your queries:

License
> absolutely. I'll pick one when I have a chance. Probably something open like MIT or something like that.

Liveview upgrade
> Great call, I just upgraded another project to latest LV and it was well worth it. Will be happy to look at any PR's and can contribute myself by updating to DynamicSupervisors and changing the indexer from sphinxsearch to manticore. Manticore is branched from the same code and is an easy swap but has some interesting feature adds.

Mariaex
> Sphinx/Manticore use sql protocol as a client to run searches. Once you have the indexer running and the connect info in the conf (if it isn't using defaults) it should be able to connect

Error crawling elixirforum
> Not sure! I've run this for months at a time just for fun and indexed hundreds of thousands of pages. I will give it a try later if I have a chance today but I recommend checking the response code with IO.inspect(). I actually should have logged failed responses so that's unfortunate you were left with the cryptic error. This project respects robots.txt but I couldn't find any rule its not following on the forum

I have a lot of feature ideas for khafra too but they require serious development.. hopefully the excuse arises to do so. But let me know if you have any issues with that project as well, hope it works well for you

**Comment by machineloop** [comment]
Great, thanks for the quick response! Appreciate the work, playing with search and index tech is an interesting challenge that's such a core part of most modern applications, you're work is making the on-ramp easier in the Elixir community.

I'll poke around more using IO.inspect and see what I come up with, thanks for the suggestion!

I just took a look at the [Manticore vs Sphinx](https://manticoresearch.com/about/), and I'm impressed that Manticore has added some key features and worked on overall performance. Would love to play more with Manticore as part of this project.

Thanks for the invitation to take a look at PRs for LiveView changes, I'll aim to send one over to you this week. Thanks again, appreciate the open source work you've put in and willingness to share!

**Comment by machineloop** [comment]
I'm fairly new to LiveView, but it actually looks like the project is pulling directly from the pheonix_liveview Github master branch, and the liveview itself looks pretty good, so there may not be a lot of work that needs to be done there...

Once I get the index up and running and pulling results into the liveview, I'll take another look.

**Comment by Tyler-pierce** [comment]
LV was pretty early back then. Cleanest way may be to upgrade to phx 1.5 (https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f) and try to use latest LV release.
Manticore and Sphinx are interesting right? No-one reaches for those tools these days but far as speed and reliability goes they've been a great match for me. I think they felt better being implemented in C++ whereas most the competitors were java based. Can't find the original blog but I liked craigslists story about scaling sphinx https://www.slideshare.net/jzawodn/mysql-and-search-at-craigslist
